// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/Delete/[user_id].tsx";
import * as $1 from "./routes/Edit/[user_id].tsx";
import * as $2 from "./routes/_404.tsx";
import * as $3 from "./routes/_app.tsx";
import * as $4 from "./routes/add.tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/DeleteButton.tsx";
import * as $$1 from "./islands/EditButton.tsx";
import * as $$2 from "./islands/EditSaveButton.tsx";
import * as $$3 from "./islands/EditValueInput.tsx";
import * as $$4 from "./islands/AddButton.tsx";
import * as $$5 from "./islands/AddSaveButton.tsx";
import * as $$6 from "./islands/AddValueInput.tsx";

const manifest = {
  routes: {
    "./routes/Delete/[user_id].tsx": $0,
    "./routes/Edit/[user_id].tsx": $1,
    "./routes/_404.tsx": $2,
    "./routes/_app.tsx": $3,
    "./routes/add.tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/DeleteButton.tsx": $$0,
    "./islands/EditButton.tsx": $$1,
    "./islands/EditSaveButton.tsx": $$2,
    "./islands/EditValueInput.tsx": $$3,
    "./islands/AddButton.tsx": $$4,
    "./islands/AddSaveButton.tsx": $$5,
    "./islands/AddValueInput.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
